import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Mail, Shield, Smartphone, UserPlus } from 'lucide-react';
const tabs = [
    { key: 'login', label: 'Connexion', helper: 'Reviens sur ta session' },
    { key: 'signup', label: 'Créer un compte', helper: '2 minutes pour lancer ta vibe' }
];
export function AuthPanel() {
    const [active, setActive] = useState('signup');
    return (_jsxs("section", { className: "glass-card auth-panel", children: [_jsxs("header", { className: "section-header", children: [_jsxs("div", { children: [_jsx("p", { children: "Authentification" }), _jsx("h2", { children: "Rejoins la communaut\u00E9 ou continue ton aventure" })] }), _jsxs("span", { className: "pill ghost", children: [_jsx(Shield, { size: 16 }), "Safe data"] })] }), _jsx("div", { className: "auth-tabs", children: tabs.map((tab) => (_jsxs("button", { className: `auth-tab ${tab.key === active ? 'active' : ''}`, onClick: () => setActive(tab.key), type: "button", children: [_jsx("span", { children: tab.label }), _jsx("small", { children: tab.helper })] }, tab.key))) }), _jsxs("form", { className: "auth-form", children: [active === 'signup' ? (_jsxs("label", { className: "field", children: [_jsx("span", { children: "Pr\u00E9nom" }), _jsx("input", { type: "text", placeholder: "ex : Salom\u00E9", required: true })] })) : null, _jsxs("label", { className: "field", children: [_jsx("span", { children: "Email" }), _jsx("input", { type: "email", placeholder: "toi@email.com", required: true })] }), _jsxs("label", { className: "field", children: [_jsx("span", { children: "Mot de passe" }), _jsx("input", { type: "password", placeholder: "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022", required: true })] }), _jsxs("label", { className: "field inline", children: [_jsx("input", { type: "checkbox", defaultChecked: true }), _jsx("span", { children: "J\u2019accepte la charte d\u2019inclusivit\u00E9, le chiffrement des messages et je veux recevoir les nouveaut\u00E9s." })] }), _jsxs("div", { className: "auth-actions", children: [_jsxs("button", { type: "submit", className: "btn primary full", children: [_jsx(UserPlus, { size: 18 }), active === 'signup' ? 'Créer mon avatar' : 'Me connecter'] }), _jsxs("button", { type: "button", className: "btn ghost full", children: [_jsx(Smartphone, { size: 18 }), "Continuer avec le mobile"] })] })] }), _jsxs("div", { className: "auth-footnote", children: [_jsx(Mail, { size: 18 }), _jsx("p", { children: "Aucun match n\u2019est rendu public sans ton accord. Tu peux exporter / supprimer ton profil depuis ton espace param\u00E8tres \u00E0 tout moment." })] })] }));
}
