import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Flame, Sparkles, Zap } from 'lucide-react';
const heroStats = [
    { label: 'Caméras activées', value: '842', trend: '+24%' },
    { label: 'Quêtes sociales', value: '62', trend: 'Live' },
    { label: 'Boost actifs', value: '118', trend: 'x2' }
];
export function Hero() {
    return (_jsxs("section", { className: "glass-card hero-card", children: [_jsxs("div", { className: "hero-header", children: [_jsxs("div", { children: [_jsx("p", { children: "Rencontre+ / Edition 2025" }), _jsx("h1", { children: "Des rencontres naturelles avec un coup de pouce intelligent." }), _jsx("p", { className: "hero-lead", children: "Choisis une qu\u00EAte, laisse l\u2019IA te proposer des affinit\u00E9s \u00E9motionnelles et rejoins des rooms audio/vid\u00E9o chaleureuses. Pas de phrases toutes faites, juste des \u00E9changes qui ressemblent \u00E0 la vraie vie." })] }), _jsxs(motion.div, { className: "hero-badge", animate: { boxShadow: ['0 0 20px rgba(255,107,139,0.4)', '0 0 0 rgba(255,107,139,0.1)'] }, transition: { duration: 2.8, repeat: Infinity }, children: [_jsx(Sparkles, { size: 18 }), _jsx("span", { children: "Invitations XR ouvertes" })] })] }), _jsxs("div", { className: "hero-cta", children: [_jsxs("button", { className: "btn primary", children: [_jsx(Flame, { size: 18 }), "Booster mon aura"] }), _jsxs("button", { className: "btn ghost", children: [_jsx(Zap, { size: 18 }), "Entrer dans une room"] })] }), _jsxs("div", { className: "hero-grid", children: [_jsxs(motion.div, { className: "hero-stream", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, children: [_jsx("p", { children: "Ce qui se passe maintenant" }), _jsxs("ul", { children: [_jsx("li", { children: "\u2022 Salom\u00E9 vient d\u2019ouvrir la qu\u00EAte \u201CBalade au canal\u201D." }), _jsx("li", { children: "\u2022 3 rooms cosy ouvrent dans 4 min." }), _jsx("li", { children: "\u2022 Boost \u00E9motionnel x2 disponible." })] })] }), _jsx("div", { className: "hero-stats", children: heroStats.map((stat) => (_jsxs("article", { children: [_jsx("strong", { children: stat.value }), _jsx("span", { children: stat.label }), _jsx("small", { children: stat.trend })] }, stat.label))) })] })] }));
}
